"""Criar tabelas iniciais

Revision ID: 1afe650edfa5
Revises: 
Create Date: 2026-01-05 19:31:38.699864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1afe650edfa5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('ix_etapas_id', table_name='etapas')
    op.drop_index('ix_etapas_processo_id', table_name='etapas')
    op.drop_table('etapas')
    op.drop_index('ix_postos_cidade', table_name='postos')
    op.drop_index('ix_postos_cnpj', table_name='postos')
    op.drop_index('ix_postos_id', table_name='postos')
    op.drop_index('ix_postos_nome', table_name='postos')
    op.drop_table('postos')
    op.drop_index('ix_processos_id', table_name='processos')
    op.drop_index('ix_processos_numero_processo', table_name='processos')
    op.drop_index('ix_processos_posto_id', table_name='processos')
    op.drop_index('ix_processos_status', table_name='processos')
    op.drop_index('ix_processos_usuario_id', table_name='processos')
    op.drop_table('processos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numero_processo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posto_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tipo_processo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['posto_id'], ['postos.id'], name='processos_posto_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='processos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='processos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_processos_usuario_id', 'processos', ['usuario_id'], unique=False)
    op.create_index('ix_processos_status', 'processos', ['status'], unique=False)
    op.create_index('ix_processos_posto_id', 'processos', ['posto_id'], unique=False)
    op.create_index('ix_processos_numero_processo', 'processos', ['numero_processo'], unique=False)
    op.create_index('ix_processos_id', 'processos', ['id'], unique=False)
    op.create_table('postos',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cep', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='postos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_postos_nome', 'postos', ['nome'], unique=False)
    op.create_index('ix_postos_id', 'postos', ['id'], unique=False)
    op.create_index('ix_postos_cnpj', 'postos', ['cnpj'], unique=False)
    op.create_index('ix_postos_cidade', 'postos', ['cidade'], unique=False)
    op.create_table('etapas',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processo_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numero_etapa', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('obrigatoria', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('data_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], name='etapas_processo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='etapas_pkey')
    )
    op.create_index('ix_etapas_processo_id', 'etapas', ['processo_id'], unique=False)
    op.create_index('ix_etapas_id', 'etapas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey')
    )
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=False)
    # ### end Alembic commands ###
